#!/usr/bin/env bash
mkdir -p brew/
rm -rf brew/*
VERSION=$(cat VERSION | cut -d '=' -f 2)

# -----------------------------------------------------------------------------
# Formula Variables -----------------------------------------------------------
# -----------------------------------------------------------------------------
DESC="Tmux Session Management written in Golang"
HOMEPAGE="https://github.com/davinche/gmux"

# Tar -------------------------------------------------------------------------
TARNAME="brew/gmux-$VERSION.tar.gz"

echo "Creating $TARNAME..."
tar -C build/macos_universal -cf $TARNAME .
tar -rf $TARNAME ./autocomplete ./install_completion.sh
gzip $TARNAME 2> /dev/null

SHA=$(shasum -a 256 $TARNAME | cut -d ' ' -f 1)

echo "Generated Formula.rb..."
cat << EOF > brew/gmux.rb
class Gmux < Formula
  desc "$DESC"
  homepage "$HOMEPAGE"
  url "https://github.com/davinche/gmux/releases/download/v$VERSION/gmux-$VERSION.tar.gz"
  sha256 "$SHA"

  bottle :unneeded

  def install
    bin.install "gmux"
    prefix.install "autocomplete"
    prefix.install "install_completion.sh"
  end

  test do
    system "#{bin}/gmux", "--version"
  end
end
EOF

echo "=========================================="
echo "*DONE*"
