#!/usr/bin/env bash

mkdir -p build/linux/amd64/
mkdir -p build/linux/arm/
mkdir -p build/linux/386/
mkdir -p build/macos/

VERSION=`cat VERSION`

env GOOS=linux GOARCH=amd64 go build -ldflags "-X main.$VERSION" -o build/linux/amd64/gmux -v
env GOOS=linux GOARCH=arm go build -ldflags "-X main.$VERSION" -o build/linux/arm/gmux -v
env GOOS=linux GOARCH=arm go build -ldflags "-X main.$VERSION" -o build/linux/386/gmux -v
env GOOS=darwin GOARCH=amd64 go build -ldflags "-X main.$VERSION" -o  build/macos/gmux -v
